import type { Metadata } from "next";
import "./globals.css";
import { SidebarDashboardClient } from "./(panel)/_components/sidebar";
import { CanvasEngineProvider } from "./contexts/canvas-engine-provider";

export const metadata: Metadata = {
  title: "Flight Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      suppressHydrationWarning
    >
      <body>
        <CanvasEngineProvider>
          <SidebarDashboardClient>
            {children}
          </SidebarDashboardClient>
        </CanvasEngineProvider>
      </body>
    </html>
  );
}
