import type { Metadata } from "next";
import "./globals.css";
import { SidebarDashboardClient } from "../components/sidebar";
import { CanvasEngineProvider } from "./contexts/canvas-engine-provider";
import { FlightPlanProvider } from "./contexts/flight-plan-provider";

export const metadata: Metadata = {
  title: "Flight Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      suppressHydrationWarning
    >
      <body>
        <CanvasEngineProvider>
          <FlightPlanProvider>
            <SidebarDashboardClient>
              {children}
            </SidebarDashboardClient>
          </FlightPlanProvider>
        </CanvasEngineProvider>
      </body>
    </html>
  );
}
